version: '3.7'

volumes:
  db:
    driver: local

services:
  db:
    container_name: uat-ask-db
    restart: always
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  app:
    container_name: uat-ask-app
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - db
    volumes:
      - /app/tmp/pids
      - .:/app
    environment:
      - PORT=3000