default: &default
  slack_bot_token: <%= ENV['BOT_TOKEN'] %>
  uat_gatekeeper: <%= ENV['GATEKEEPER'] %>
  admin_slack_ids: <%= ENV['ADMINS'] %>
  slack_email_domain: <%= ENV['SLACK_DOMAIN'] %>

development: 
  <<: *default

test: 
  <<: *default

production: 
  <<: *default