defaults: &defaults
  adapter: mysql2
  host: 'db'
  pool: 10
  reconnect: true
  encoding: utf8
  username: root
  database: 'uatask'
  port: 3306

development:
  <<: *defaults
  password:

test:
  <<: *defaults
  password:

production:
  <<: *defaults
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
