defaults: &defaults
  adapter: mysql2
  host: localhost
  pool: 10
  reconnect: true
  encoding: utf8
  database: #TODO

development:
  <<: *defaults
  username: root
  password:
  port: 3306

production:
  <<: *defaults
  host: #TODO
  database: #TODO
  username: #TODO
  password: #TODO

test:
  <<: *defaults
  username: root
  password:
  port: 3306
