defaults: &defaults
  adapter: mysql2
  host: <%= ENV['HOST'] %>
  pool: 10
  reconnect: true
  encoding: utf8
  username: root
  database: <%= ENV['DB_NAME'] || 'uatask' %>

development:
  <<: *defaults
  username: root
  password:
  port: 3306

test:
  <<: *defaults
  password:
  port: 3306

production:
  <<: *defaults
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
